# Generated by Django 3.2.12 on 2022-04-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyplan', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Note', models.CharField(max_length=200)),
            ],
        ),
    ]
