# Generated by Django 3.2.12 on 2022-04-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyplan', '0003_session_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP_TAB', models.CharField(max_length=200)),
                ('LNAME', models.CharField(max_length=200)),
                ('FNAME', models.CharField(max_length=200)),
                ('MNAME', models.CharField(max_length=200)),
                ('DOLGN', models.CharField(max_length=200)),
                ('PODRAZ', models.CharField(max_length=200)),
            ],
        ),
    ]
