# Generated by Django 3.2.12 on 2022-04-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyplan', '0004_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Instructors',
        ),
    ]
