# Generated by Django 3.2.12 on 2022-04-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyplan', '0005_rename_instructor_instructors'),
    ]

    operations = [
        migrations.CreateModel(
            name='freelance_instructor_pilots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP_TAB', models.CharField(max_length=200)),
                ('FULL_NAME', models.CharField(max_length=200)),
                ('DOLGN', models.CharField(max_length=200)),
                ('PODRAZ', models.CharField(max_length=200)),
                ('DAT_PROV', models.DateTimeField()),
                ('DAT_TREN', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='freelance_instructor_pilots_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP_TAB', models.CharField(max_length=200)),
                ('FULL_NAME', models.CharField(max_length=200)),
                ('DOLGN', models.CharField(max_length=200)),
                ('PODRAZ', models.CharField(max_length=200)),
                ('DAT_PROV', models.DateTimeField()),
                ('DAT_TREN', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KRS_according_staff_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP_TAB', models.CharField(max_length=200)),
                ('FULL_NAME', models.CharField(max_length=200)),
                ('DOLGN', models.CharField(max_length=200)),
                ('PODRAZ', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KRS_LIS_air_squadrons_according_staffing_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAP_TAB', models.CharField(max_length=200)),
                ('FULL_NAME', models.CharField(max_length=200)),
                ('DOLGN', models.CharField(max_length=200)),
                ('PODRAZ', models.CharField(max_length=200)),
            ],
        ),
    ]
