# Generated by Django 3.2.12 on 2022-05-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyplan', '0007_auto_20220414_1625'),
        ('pyplan', '0008_rename_podraz_instructors_group_and_more'),
    ]

    operations = [
    ]
